### ISSUE TITLE
doesn't instance the models on the terrain [MacOs]

### ISSUE THREAD

**Issue by ardawan** [Zylann/godot_scatter_plugin#1]
- I've pasted "zylann.scatter" next to "zylann.hterrain" in the addons folder.
- activated the plugin from the godo plugin setting.
- created a 3d scene
  - added hterrain
  - directional light
  - scatter 3D
- select on the scatter node and add the 3d scene that i wish to instance it
- tried to click and drag on the terrain but i got error in the output.

```
res://addons/zylann.scatter/tools/plugin.gd:159 - Attempt to call function 'get_parent' in base 'null instance' on a null instance.
Paint scenes
```

is that a bug or im not following the instructions?

**Comment by Zylann** [comment]
It is a bug coming from both plugins:

- The terrain plugin is not registering its node to the collision queries, so when you get the result from a raycast, `collider` is `null`. This is not always a bug (if there is no node to refer to), but in this case it is because there is no reason to not provide the terrain node you hit.

- The scatter plugin assumes `collider` is never `null`, but nothing enforces that in the Godot API. Fortunately, it's an easy fix because it's only needed to ensure the scatter layer isn't colliding with itself. In case `collider` is `null`, it should just pass the check.

Sorry for the very late answer, Github doesn't notify me of new issues...

**Comment by Zylann** [comment]
I fixed the error in this plugin in 92ffa27a37206aa9dc93c1d5567209b218c363d9
You can try with the `master` version of the plugin from this repo.

**Comment by pwab** [comment]
I'm not getting that error but it still does not instance a scene into my parent scene. It only says `Paint scenes`, my world-scene wants to be saved because of changes but nothing has changed at all.

Is the error on my side? (Side note: Using Godot 3.1 stable and version 1.0.1 of your plugin from the AssetStore)

**Screenshot:**
![scattering](https://user-images.githubusercontent.com/19271185/67163222-9eef2100-f36c-11e9-99a3-822f052287d2.png)

**Testproject:**
[scattering.zip](https://github.com/Zylann/godot_scatter_plugin/files/3748093/scattering.zip)

**Comment by Zylann** [comment]
@pwab in your case there is nothing to paint onto. That's why nothing happens, your scene is empty (doesn't even have a floor). This plugin relies on existence of a floor with collision.

**Comment by pwab** [comment]
Oh thanks for the clarification. So I need a Staticbody as a ground?

Maybe there could be one or two sentences about the usage of the plugin. I barely can see the process of adding things in the provided gif. Maybe add a short numbered list with each step?

**Comment by Zylann** [comment]
@pwab I added details https://github.com/Zylann/godot_scatter_plugin/blob/master/README.md#how-to-use

**Comment by pwab** [comment]
Works perfectly now. Thanks 👍
